"""add account_number and bank_branch to accounts

Revision ID: 40bc0620e0c6
Revises: 0f1b81015c9f
Create Date: 2026-09-28 14:30:22.908149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bc0620e0c6'
down_revision = '0f1b81015c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_branch', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('bank_branch')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
