"""add fixed assets and payroll tables

Revision ID: 4f5add5c3c87
Revises: ea8765bf3375
Create Date: 2026-09-26 09:58:42.758653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5add5c3c87'
down_revision = 'ea8765bf3375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.String(length=30), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role_title', sa.String(length=150), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('basic_salary', sa.Float(), nullable=True),
    sa.Column('housing_allowance', sa.Float(), nullable=True),
    sa.Column('transport_allowance', sa.Float(), nullable=True),
    sa.Column('other_allowance', sa.Float(), nullable=True),
    sa.Column('pension_opt_in', sa.Boolean(), nullable=True),
    sa.Column('nhf_opt_in', sa.Boolean(), nullable=True),
    sa.Column('annual_rent', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'staff_id', name='uq_employee_org_staffid')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_organization_id'), ['organization_id'], unique=False)

    op.create_table('fixed_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('custodian', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('salvage_value', sa.Float(), nullable=True),
    sa.Column('useful_life_years', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_value', sa.Float(), nullable=True),
    sa.Column('last_depreciated_on', sa.Date(), nullable=True),
    sa.Column('acquisition_entry_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixed_assets_organization_id'), ['organization_id'], unique=False)

    op.create_table('payroll_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_runs_organization_id'), ['organization_id'], unique=False)

    op.create_table('payslips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('gross', sa.Float(), nullable=True),
    sa.Column('pension_employee', sa.Float(), nullable=True),
    sa.Column('pension_employer', sa.Float(), nullable=True),
    sa.Column('nhf', sa.Float(), nullable=True),
    sa.Column('paye', sa.Float(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslips_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_organization_id'))

    op.drop_table('payslips')
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_runs_organization_id'))

    op.drop_table('payroll_runs')
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixed_assets_organization_id'))

    op.drop_table('fixed_assets')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_organization_id'))

    op.drop_table('employees')
    # ### end Alembic commands ###
