"""pay now: payment settings, invoice payments, share links

Revision ID: 87773fec0a50
Revises: be8a37c18d91
Create Date: 2026-10-10 01:01:47.907625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87773fec0a50'
down_revision = 'be8a37c18d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paystack_secret_enc', sa.Text(), nullable=True),
    sa.Column('paystack_key_hint', sa.String(length=40), nullable=True),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('show_bank_details', sa.Boolean(), nullable=False),
    sa.Column('bank_instructions', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_payment_settings_org')
    )
    with op.batch_alter_table('payment_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_settings_organization_id'), ['organization_id'], unique=False)

    op.create_table('invoice_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('payer_name', sa.String(length=150), nullable=True),
    sa.Column('payer_email', sa.String(length=150), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_payments_organization_id'), ['organization_id'], unique=False)

    op.create_table('invoice_share_links',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('token'),
    sa.UniqueConstraint('invoice_id')
    )
    with op.batch_alter_table('invoice_share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_share_links_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_share_links_organization_id'))

    op.drop_table('invoice_share_links')
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_payments_invoice_id'))

    op.drop_table('invoice_payments')
    with op.batch_alter_table('payment_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_settings_organization_id'))

    op.drop_table('payment_settings')
    # ### end Alembic commands ###
