"""add is_demo flag to organizations

Revision ID: c3041694e8d3
Revises: 2f9702c2a608
Create Date: 2026-09-26 11:55:06.157288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3041694e8d3'
down_revision = '2f9702c2a608'
branch_labels = None
depends_on = None


def upgrade():
    # Existing rows have no value for a brand-new NOT NULL column, so a
    # server-side default is required for the ALTER TABLE itself to
    # succeed against organizations created before this migration.
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    # ### end Alembic commands ###
